2018-06-16 23:19:41 [INFO] | | OPEN | HIGH | LOW | CLOSE | LAST PRICE | BUY | SELL |
2018-06-16 23:19:41 [INFO] | RESUMEN | 317000.0 | 317000.0 | 317000.0 | 317000.0 | 317000.0 |  |  |
Traceback (most recent call last):
  File "/home/tito/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 52, in <module>
    hstNew.getHistory(False, mkt)
  File "/home/tito/Documentos/Lab/titoLab/py/Buda/History.py", line 37, in getHistory
    res = requests.get(url)
  File "/home/tito/.local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/tito/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/tito/.local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tito/.local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/tito/.local/lib/python3.6/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/home/tito/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/tito/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt
2018-06-16 23:35:04 [INFO] | | OPEN | HIGH | LOW | CLOSE | LAST PRICE | BUY | SELL |
2018-06-16 23:35:04 [INFO] | RESUMEN | 317000.0 | 317000.0 | 317000.0 | 317000.0 | 317000.0 |  |  |
2018-06-16 23:42:33 [INFO] | | OPEN | HIGH | LOW | CLOSE | LAST PRICE | BUY | SELL |
2018-06-16 23:42:33 [INFO] | RESUMEN | 0.0 | 0.0 | 0.0 | 0.0 | 0.0 |  |  |
2018-06-16 23:42:36 [INFO] | RESUMEN | 317000.0 | 317000.0 | 317000.0 | 317000.0 | 317000.0 |  |  | 
2018-06-16 23:58:34 [INFO] | RESUMEN | 317000.0 | 317100.0 | 317000.0 | 317100.0 | 317000.0 |  |  | 
2018-06-16 23:58:58 [INFO] | RESUMEN | 317000.0 | 317100.0 | 317000.0 | 317100.0 | 317100.0 |  |  | 
2018-06-17 00:07:58 [INFO] | RESUMEN | 317000.0 | 328844.78 | 317000.0 | 328844.78 | 317100.0 |  |  | 
2018-06-17 00:08:07 [INFO] | RESUMEN | 317000.0 | 328844.78 | 317000.0 | 328844.78 | 328844.78 |  |  | 
